development:
  adapter: postgresql
  encoding: unicode
  database: rails42_qc_31_dev
  pool: 50
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails42_qc_31_test
  pool: 5
  username: postgres
  password:
